- hosts : localhost
  connection: local
  become: true

  pre_tasks:
    - name: update repository
      apt: 
        update_cache: yes
      changed_when: false
      when : ansible_distribution == "Debian"

    - name: update repository
      dnf: 
        update_cache: yes 
      changed_when: false
      when : ansible_distribution == "CentOS"

  tasks:
    - include: tasks/packages.yml

