- name: Install packages for Debian
  apt:
    name: 
      - htop
      - mc
      - tmux
      - tree
      - neovim
      - locales
      - zip
      - unzip
      - npm
      - gnupg
      - lsb-release
      - ca-certificates
    state: latest
  when: ansible_distribution == "Debian"

- name: Install packages fro CentOS
  dnf:
    name: 
      - htop
      - mc
      - tmux
      - tree
      - neovim
      - glibc-common
      - zip
      - unzip
      - npm
      - gnupg
      - ca-certificates
    state: latest
  when: ansible_distribution == "CentOS"
