- name: Install htop
  package:
    name: 
      - htop
      - mc
      - tmux
      - tree
      - neovim
      - locales
      - zip
      - unzip
      - npm
      - gnupg
      - lsb-release
      - ca-certificates
    state: latest
